background = 0xFF1e1e2e
base = 0xFF1e1e2e
text = 0xFFcdd6f4
alternate_base = 0xFF181825
bright_text = 0xFFcdd6f4
accent = 0xFF89b4fa
accent_secondary = 0xFFcba6f7

rounding_large = 0
rounding_small = 0

font_family = VT323
font_family_monospace = VT323
font_size = 12
