env = XCURSOR_SIZE,16

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    no_gaps_when_only = true
}

# Window opacity
windowrulev2 = opacity 0.8, class:^(nm-connection-editor|Nm-connection-editor)$
