env = XCURSOR_SIZE,24
env = XCURSOR_THEME,catppuccin-mocha-mauve-cursors
env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,catppuccin-mocha-mauve-cursors
env = QT_QPA_PLATFORMTHEME,qt6ct;qt5ct

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    no_gaps_when_only = true
}

exec-once = swaybg -i /home/vroomer/Downloads/12259305.png -m fill

# Window opacity
windowrulev2 = opacity 0.8, class:^(nm-connection-editor|Nm-connection-editor)$
windowrulev2 = opacity 0.85 0.85, class:^(discord|Discord)$
windowrulev2 = opacity 0.85 0.85, class:^(Spotify|spotify)$
windowrulev2 = opacity 0.85 0.85, class:^(firefox|Firefox|firefox-esr)$
